from .department import DepartmentService
from .specialty import SpecialtyService
from .specialization import SpecializationService
from .education_component import EducationComponentService
from .study_group import StudyGroupService
from .semester import SemesterService
from .academic_hours import AcademicHoursService
from .academic_task import AcademicTaskService
from .curriculum import CurriculumService
from .user import UserService
