from .exception import UnauthorizedException, ForbiddenException
from .not_found import (NotFoundException,
                        DepartmentNotFoundException,
                        SpecialtyNotFoundException,
                        SpecializationNotFoundException,
                        EducationComponentNotFoundException,
                        StudyGroupNotFoundException,
                        SemesterNotFoundException,
                        AcademicHoursNotFoundException,
                        AcademicTaskNotFoundException,
                        CurriculumNotFoundException,
                        UserNotFoundException)
from .conflict import (ConflictException,
                       DepartmentConflictException,
                       SpecialtyConflictException,
                       SpecializationConflictException,
                       EducationComponentConflictException,
                       StudyGroupConflictException,
                       SemesterConflictException,
                       AcademicHoursConflictException,
                       AcademicTaskConflictException,
                       UserConflictException)
