from .academic_hours import AcademicHoursModel
from .academic_task import AcademicTaskModel
from .academic_workload import AcademicWorkloadModel
from .academic_workload_formula import AcademicWorkloadFormulaModel
from .department import DepartmentModel
from .education_component import EducationComponentModel
from .many_to_many_tables import EducationComponentsStudyGroupsModel
from .semester import SemesterModel
from .specialization import SpecializationModel
from .specialty import SpecialtyModel
from .study_group import StudyGroupModel
from .teacher import TeacherModel
from .user import UserModel
