from .department import DepartmentModel
from .specialty import SpecialtyModel
from .specialization import SpecializationModel
from .education_component import EducationComponentModel
from .semester import SemesterModel
from .academic_hours import AcademicHoursModel
from .academic_task import AcademicTaskModel
from .study_group import StudyGroupModel
from .many_to_many_tables import EducationComponentsStudyGroupsModel
from .user import UserModel
